package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Bulgarian] = map[string]string{
		"#admin":                              "администратор",
		"#admin.allow-role":                   "позволи-роля",
		"#look":                               "виж",
		"#move":                               "ход",
		"#review":                             "преглед",
		"#admin.allow-role.value":             "стойност",
		"#.subject":                           "мишена",
		"#look.info":                          "информация",
		"#look.reviews":                       "прегледи",
		"#admin.allow-role.Description":       "Показване на резултати като роли. По подразбиране: False",
		"#look.Description":                   "виж нещо",
		"#move.Description":                   "Преместете рецензията в този канал",
		"#review.Description":                 "Потребителски преглед",
		"#admin.allow-role.value.Description": "зададена стойност",
		"#.subject.Description":               "Изберете цел",
		"#look.info.Description":              "Вижте потребителска информация",
		"#look.reviews.Description":           "Вижте отзивите, които обектът е получил",
		"#admin.allow-role.NeedPermissions":   "На бота липсват разрешения - Управление на роли",
		"#admin.allow-role.InProgress":        "работа в прогрес",
		"#admin.allow-role.proc.Title":        "Опции за промяна",
		"#admin.allow-role.proc.Description":  "Разрешаване на роли",
		"#admin.allow-role.proc.InProgress":   "Процедура",
		"#admin.allow-role.proc.Done":         "пълен",
		"#admin.allow-role.Keep":              "Няма променени настройки",
		"#look.info.IsNone":                   "Няма отзиви",
		"#look.reviews.IsNone":                "Няма отзиви",
		"#look.reviews.menu.Title":            "Отзиви за %v",
		"#look.reviews.menu.Page":             "%v страница",
		"#move.IsNone":                        "Няма написани рецензии за целта",
		"#move.Move":                          "премести се тук",
		"#review.SelfReview":                  "Не можете да прегледате себе си",
		"#review.modal.Title":                 "Преглед на %v",
		"#review.lable.Score":                 "резултат",
		"#review.lable.Title":                 "заглавие",
		"#review.lable.Content":               "детайл",
		"$review.IsEdited":                    "Тази рецензия е редактирана",
		"$review.NoAuthor":                    "Изтритите рецензии не могат да бъдат възстановени, защото авторът не съществува тук",
		"$review.DM":                          "Написана е нова рецензия",
	}
}
