package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.ChineseTW] = map[string]string{
		"#admin":                              "行政",
		"#admin.allow-role":                   "允許角色",
		"#look":                               "看",
		"#move":                               "移動",
		"#review":                             "審查",
		"#admin.allow-role.value":             "價值",
		"#.subject":                           "目標",
		"#look.info":                          "資訊",
		"#look.reviews":                       "評論",
		"#admin.allow-role.Description":       "將分數顯示為角色。預設值：假",
		"#look.Description":                   "看到一些東西",
		"#move.Description":                   "將評論移至此頻道",
		"#review.Description":                 "用戶評論",
		"#admin.allow-role.value.Description": "設定值",
		"#.subject.Description":               "選擇目標",
		"#look.info.Description":              "查看使用者資訊",
		"#look.reviews.Description":           "查看該主題收到的評論",
		"#admin.allow-role.NeedPermissions":   "機器人缺乏權限 - 管理角色",
		"#admin.allow-role.InProgress":        "工作正在進行中",
		"#admin.allow-role.proc.Title":        "修改選項",
		"#admin.allow-role.proc.Description":  "允許角色",
		"#admin.allow-role.proc.InProgress":   "論文集",
		"#admin.allow-role.proc.Done":         "完全的",
		"#admin.allow-role.Keep":              "沒有更改設定",
		"#look.info.IsNone":                   "沒有評論",
		"#look.reviews.IsNone":                "沒有評論",
		"#look.reviews.menu.Title":            "對 %v 的評論",
		"#look.reviews.menu.Page":             "%v 頁",
		"#move.IsNone":                        "沒有為目標撰寫評論",
		"#move.Move":                          "搬來這",
		"#review.SelfReview":                  "你無法檢討自己",
		"#review.modal.Title":                 "評論 %v",
		"#review.lable.Score":                 "分數",
		"#review.lable.Title":                 "標題",
		"#review.lable.Content":               "細節",
		"$review.IsEdited":                    "此評論已編輯",
		"$review.NoAuthor":                    "已刪除的評論無法恢復，因為這裡不存在作者",
		"$review.DM":                          "已撰寫新評論",
	}
}
