package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Finnish] = map[string]string{
		"#admin":                              "järjestelmänvalvoja",
		"#admin.allow-role":                   "salli-roolin",
		"#look":                               "katso",
		"#move":                               "liikkua",
		"#review":                             "arvostelu",
		"#admin.allow-role.value":             "arvo",
		"#.subject":                           "kohde",
		"#look.info":                          "tiedot",
		"#look.reviews":                       "arvostelut",
		"#admin.allow-role.Description":       "Näytä tulokset rooleina. Oletus: False",
		"#look.Description":                   "nähdä jotain",
		"#move.Description":                   "Siirrä arvostelu tälle kanavalle",
		"#review.Description":                 "Käyttäjän arvostelu",
		"#admin.allow-role.value.Description": "aseta arvo",
		"#.subject.Description":               "Valitse kohde",
		"#look.info.Description":              "Katso käyttäjätiedot",
		"#look.reviews.Description":           "Katso aiheen saamat arvostelut",
		"#allow-role.NeedPermissions":         "Botilla ei ole käyttöoikeuksia - Hallitse rooleja",
		"#allow-role.InProgress":              "Työn alla",
		"#allow-role.proc.Title":              "Muokkaa asetuksia",
		"#allow-role.proc.Description":        "Salli roolit",
		"#allow-role.proc.InProgress":         "Jatketaan",
		"#allow-role.proc.Done":               "saattaa loppuun",
		"#allow-role.Keep":                    "Ei asetuksia muutettu",
		"#look.info.IsNone":                   "Ei arvosteluja",
		"#look.reviews.IsNone":                "Ei arvosteluja",
		"#look.reviews.menu.Title":            "Arvostelut kohteelle %s",
		"#look.reviews.menu.Page":             "%d sivu",
		"#move.IsNone":                        "Kohteelle ei ole kirjoitettu arvosteluja",
		"#move.Move":                          "muuta tänne",
		"#review.SelfReview":                  "Et voi arvostella itseäsi",
		"#review.modal.Title":                 "Arvostelut",
		"#review.lable.Score":                 "pisteet",
		"#review.lable.Title":                 "otsikko",
		"#review.lable.Content":               "yksityiskohta",
		"$review.IsEdited":                    "Tätä arvostelua on muokattu",
		"$review.NoAuthor":                    "Poistettuja arvosteluja ei voi palauttaa, koska kirjoittajaa ei ole täällä",
		"$review.DM":                          "Uusi arvostelu on kirjoitettu",
    }
}
