package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.French] = map[string]string{
		"#admin":                              "administrateur",
		"#admin.allow-role":                   "autoriser-le-rôle",
		"#look":                               "regarder",
		"#move":                               "se-déplacer",
		"#review":                             "revoir",
		"#admin.allow-role.value":             "valeur",
		"#.subject":                           "cible",
		"#look.info":                          "information",
		"#look.reviews":                       "commentaires",
		"#admin.allow-role.Description":       "Afficher les scores sous forme de rôles. Par défaut : Faux",
		"#look.Description":                   "voir quelque chose",
		"#move.Description":                   "Déplacer l'avis vers cette chaîne",
		"#review.Description":                 "Avis d'utilisateur",
		"#admin.allow-role.value.Description": "valeur définie",
		"#.subject.Description":               "Sélectionnez la cible",
		"#look.info.Description":              "Afficher les informations sur l'utilisateur",
		"#look.reviews.Description":           "Voir les avis que le sujet a reçus",
		"#allow-role.NeedPermissions":         "Le bot ne dispose pas d'autorisations - Gérer les rôles",
		"#allow-role.InProgress":              "travail en cours",
		"#allow-role.proc.Title":              "Modifier les options",
		"#allow-role.proc.Description":        "Autoriser les rôles",
		"#allow-role.proc.InProgress":         "Procédure en cours",
		"#allow-role.proc.Done":               "complet",
		"#allow-role.Keep":                    "Aucun paramètre modifié",
		"#look.info.IsNone":                   "Aucun avis",
		"#look.reviews.IsNone":                "Il n'y a pas de commentaires",
		"#look.reviews.menu.Title":            "Commentaires pour %s",
		"#look.reviews.menu.Page":             "%d pages",
		"#move.IsNone":                        "Il n'y a aucun avis écrit pour la cible",
		"#move.Move":                          "bouge ici",
		"#review.SelfReview":                  "Vous ne pouvez pas vous réviser",
		"#review.modal.Title":                 "Commentaires",
		"#review.lable.Score":                 "score",
		"#review.lable.Title":                 "titre",
		"#review.lable.Content":               "détail",
		"$review.IsEdited":                    "Cet avis a été modifié",
		"$review.NoAuthor":                    "Les avis supprimés ne peuvent pas être restaurés car l'auteur n'existe pas ici",
		"$review.DM":                          "Une nouvelle critique a été rédigée",
    }
}
