package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.German] = map[string]string{
		"#allow-role":                   "rollenzulässig",
		"#look":                         "sehen",
		"#move":                         "bewegen",
		"#review":                       "rezension",
		"#allow-role.value":             "wert",
		"#.subject":                     "ziel",
		"#look.info":                    "information",
		"#look.review-list":             "rezensionsliste",
		"#allow-role.Description":       "Nur Administrator – Standard: Falsch",
		"#look.Description":             "etwas besichtigen",
		"#move.Description":             "Rezension auf diesen Kanal verschieben",
		"#review.Description":           "Nutzerbewertung",
		"#allow-role.value.Description": "Wert einstellen",
		"#.subject.Description":         "Ziel auswählen",
		"#look.info.Description":        "Benutzerinformationen anzeigen",
		"#look.review-list.Description": "Sehen Sie sich die Liste der von Benutzern erhaltenen Bewertungen an",
		"#allow-role.NeedPermissions":   "Dem Bot fehlen Berechtigungen – Rollen verwalten",
		"#allow-role.InProgress":        "in Arbeit",
		"#allow-role.proc.Title":        "Optionen ändern",
		"#allow-role.proc.Description":  "Rollenberechtigung",
		"#allow-role.proc.InProgress":   "Weiter",
		"#allow-role.proc.Done":         "vollständig",
		"#allow-role.Keep":              "Keine Einstellungen geändert",
		"#look.info.IsNone":             "Keine Bewertungen",
		"#look.review-list.IsNone":      "Es gibt keine Bewertungen",
		"#look.review-list.menu.Title":  "Bewertungen für %s",
		"#look.review-list.menu.Page":   "%d Seite",
		"#move.IsNone":                  "Für das Ziel liegen keine Rezensionen vor",
		"#move.Move":                    "Komm her",
		"#review.SelfReview":            "Sie können sich nicht selbst bewerten",
		"#review.modal.Title":           "Überprüfen Sie %s",
		"#review.lable.Score":           "Punktzahl",
		"#review.lable.Title":           "Titel",
		"#review.lable.Content":         "Detail",
		"$review.IsEdited":              "Diese Rezension wurde bearbeitet",
		"$review.NoAuthor":              "Gelöschte Rezensionen können nicht wiederhergestellt werden, da der Autor hier nicht existiert",
		"$review.DM":                    "Eine neue Rezension wurde verfasst",
	}
}
