package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Hindi] = map[string]string{
		"#admin":                              "व्यवस्थापक",
		"#admin.allow-role":                   "भूमिका-की-अनुमति-दें",
		"#look":                               "देखना",
		"#move":                               "कदम",
		"#review":                             "समीक्षा",
		"#admin.allow-role.value":             "कीमत",
		"#.subject":                           "लक्ष्य",
		"#look.info":                          "जानकारी",
		"#look.reviews":                       "समीक्षा",
		"#admin.allow-role.Description":       "स्कोर को भूमिकाओं के रूप में प्रदर्शित करें। डिफ़ॉल्ट: ग़लत",
		"#look.Description":                   "कुछ देखें",
		"#move.Description":                   "समीक्षा को इस चैनल पर ले जाएं",
		"#review.Description":                 "उपयोगकर्ता समीक्षा",
		"#admin.allow-role.value.Description": "मूल्य ते करना",
		"#.subject.Description":               "लक्ष्य चुनें",
		"#look.info.Description":              "उपयोगकर्ता जानकारी देखें",
		"#look.reviews.Description":           "विषय को प्राप्त समीक्षाएँ देखें",
		"#admin.allow-role.NeedPermissions":   "बॉट में अनुमतियों का अभाव है - भूमिकाएँ प्रबंधित करें",
		"#admin.allow-role.InProgress":        "कार्य प्रगति पर है",
		"#admin.allow-role.proc.Title":        "विकल्प संशोधित करें",
		"#admin.allow-role.proc.Description":  "भूमिकाओं की अनुमति दें",
		"#admin.allow-role.proc.InProgress":   "कार्यवाही",
		"#admin.allow-role.proc.Done":         "पूरा",
		"#admin.allow-role.Keep":              "कोई सेटिंग नहीं बदली",
		"#look.info.IsNone":                   "कोई समीक्षा नहीं",
		"#look.reviews.IsNone":                "कोई समीक्षा नहीं है",
		"#look.reviews.menu.Title":            "%s के लिए समीक्षाएँ",
		"#look.reviews.menu.Page":             "%d पेज",
		"#move.IsNone":                        "लक्ष्य के लिए कोई समीक्षा नहीं लिखी गई है",
		"#move.Move":                          "यहां स्थानांतर करो",
		"#review.SelfReview":                  "आप स्वयं की समीक्षा नहीं कर सकते",
		"#review.modal.Title":                 "%s की समीक्षा करें",
		"#review.lable.Score":                 "अंक",
		"#review.lable.Title":                 "शीर्षक",
		"#review.lable.Content":               "विवरण",
		"$review.IsEdited":                    "यह समीक्षा संपादित की गई है",
		"$review.NoAuthor":                    "हटाई गई समीक्षाओं को पुनर्स्थापित नहीं किया जा सकता क्योंकि लेखक यहां मौजूद नहीं है",
		"$review.DM":                          "एक नई समीक्षा लिखी गई है",
	}
}
