package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Hungarian] = map[string]string{
		"#admin":                              "admin",
		"#admin.allow-role":                   "szerepet-engedélyez",
		"#look":                               "néz",
		"#move":                               "mozog",
		"#review":                             "felülvizsgálat",
		"#admin.allow-role.value":             "érték",
		"#.subject":                           "cél",
		"#look.info":                          "információ",
		"#look.reviews":                       "vélemények",
		"#admin.allow-role.Description":       "A pontszámok megjelenítése szerepként. Alapértelmezett: False",
		"#look.Description":                   "látni valamit",
		"#move.Description":                   "Vélemény áthelyezése erre a csatornára",
		"#review.Description":                 "Felhasználói vélemény",
		"#admin.allow-role.value.Description": "Érték beállítása",
		"#.subject.Description":               "Válassza ki a célt",
		"#look.info.Description":              "Felhasználói adatok megtekintése",
		"#look.reviews.Description":           "Tekintse meg az alany által kapott értékeléseket",
		"#admin.allow-role.NeedPermissions":   "A robotnak nincsenek engedélyei – Szerepkörök kezelése",
		"#admin.allow-role.InProgress":        "munka folyamatban",
		"#admin.allow-role.proc.Title":        "Beállítások módosítása",
		"#admin.allow-role.proc.Description":  "Szerepek engedélyezése",
		"#admin.allow-role.proc.InProgress":   "Folytatás",
		"#admin.allow-role.proc.Done":         "teljes",
		"#admin.allow-role.Keep":              "A beállítások nem változtak",
		"#look.info.IsNone":                   "Nincs vélemény",
		"#look.reviews.IsNone":                "Nincsenek értékelések",
		"#look.reviews.menu.Title":            "Vélemények a következőről: %s",
		"#look.reviews.menu.Page":             "%d oldal",
		"#move.IsNone":                        "Nincsenek értékelések a célpontról",
		"#move.Move":                          "Gyere ide",
		"#review.SelfReview":                  "Nem tudod felülvizsgálni magad",
		"#review.modal.Title":                 "Tekintse át: %s",
		"#review.lable.Score":                 "pontszám",
		"#review.lable.Title":                 "cím",
		"#review.lable.Content":               "Részlet",
		"$review.IsEdited":                    "Ezt a véleményt szerkesztették",
		"$review.NoAuthor":                    "A törölt véleményeket nem lehet visszaállítani, mert a szerző nem létezik itt",
		"$review.DM":                          "Új értékelés készült",
	}
}
