package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Italian] = map[string]string{
		"#admin":                              "amministratore",
		"#admin.allow-role":                   "consentire-il-ruolo",
		"#look":                               "aspetto",
		"#move":                               "mossa",
		"#review":                             "revisione",
		"#admin.allow-role.value":             "valore",
		"#.subject":                           "bersaglio",
		"#look.info":                          "informazione",
		"#look.reviews":                       "recensioni",
		"#admin.allow-role.Description":       "Visualizza i punteggi come ruoli. Predefinito: falso",
		"#look.Description":                   "vedere qualcosa",
		"#move.Description":                   "Sposta la recensione su questo canale",
		"#review.Description":                 "Recensione dell'utente",
		"#admin.allow-role.value.Description": "Valore impostato",
		"#.subject.Description":               "Seleziona destinazione",
		"#look.info.Description":              "Visualizza le informazioni dell'utente",
		"#look.reviews.Description":           "Visualizza le recensioni ricevute dall'argomento",
		"#admin.allow-role.NeedPermissions":   "Il bot non dispone delle autorizzazioni: Gestisci ruoli",
		"#admin.allow-role.InProgress":        "lavori in corso",
		"#admin.allow-role.proc.Title":        "Modifica opzioni",
		"#admin.allow-role.proc.Description":  "Consenti ruoli",
		"#admin.allow-role.proc.InProgress":   "Procedere",
		"#admin.allow-role.proc.Done":         "completare",
		"#admin.allow-role.Keep":              "Nessuna impostazione modificata",
		"#look.info.IsNone":                   "Nessuna recensione",
		"#look.reviews.IsNone":                "Non ci sono recensioni",
		"#look.reviews.menu.Title":            "Recensioni per %s",
		"#look.reviews.menu.Page":             "%d pagina",
		"#move.IsNone":                        "Non ci sono recensioni scritte per il target",
		"#move.Move":                          "Vieni qui",
		"#review.SelfReview":                  "Non puoi rivedere te stesso",
		"#review.modal.Title":                 "Recensioni",
		"#review.lable.Score":                 "punto",
		"#review.lable.Title":                 "titolo",
		"#review.lable.Content":               "dettaglio",
		"$review.IsEdited":                    "Questa recensione è stata modificata",
		"$review.NoAuthor":                    "Le recensioni cancellate non possono essere ripristinate perché l'autore non esiste qui",
		"$review.DM":                          "È stata scritta una nuova recensione",
	}
}
