package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Polish] = map[string]string{
		"#admin":                              "admin",
		"#admin.allow-role":                   "pozwolić-na-rolę",
		"#look":                               "patrzeć",
		"#move":                               "przenosić",
		"#review":                             "recenzja",
		"#admin.allow-role.value":             "wartość",
		"#.subject":                           "cel",
		"#look.info":                          "informacja",
		"#look.reviews":                       "opinie",
		"#admin.allow-role.Description":       "Wyświetlaj wyniki jako role. Wartość domyślna: Fałsz",
		"#look.Description":                   "zobaczyć coś",
		"#move.Description":                   "Przenieś recenzję na ten kanał",
		"#review.Description":                 "Opinia użytkownika",
		"#admin.allow-role.value.Description": "Ustalić wartość",
		"#.subject.Description":               "Wybierz cel",
		"#look.info.Description":              "Wyświetl informacje o użytkowniku",
		"#look.reviews.Description":           "Zobacz recenzje, jakie otrzymał temat",
		"#admin.allow-role.NeedPermissions":   "Bot nie ma uprawnień - Zarządzaj rolami",
		"#admin.allow-role.InProgress":        "Praca w toku",
		"#admin.allow-role.proc.Title":        "Zmień opcje",
		"#admin.allow-role.proc.Description":  "Zezwalaj na role",
		"#admin.allow-role.proc.InProgress":   "Postępowanie",
		"#admin.allow-role.proc.Done":         "kompletny",
		"#admin.allow-role.Keep":              "Żadne ustawienia nie uległy zmianie",
		"#look.info.IsNone":                   "Brak recenzji",
		"#look.reviews.IsNone":                "Brak recenzji",
		"#look.reviews.menu.Title":            "Recenzje %v",
		"#look.reviews.menu.Page":             "%v strona",
		"#move.IsNone":                        "Dla celu nie napisano żadnych recenzji",
		"#move.Move":                          "przesuń się tutaj",
		"#review.SelfReview":                  "Nie możesz sam dokonać przeglądu",
		"#review.modal.Title":                 "Opinie",
		"#review.lable.Score":                 "wynik",
		"#review.lable.Title":                 "tytuł",
		"#review.lable.Content":               "Szczegół",
		"$review.IsEdited":                    "Ta recenzja została poprawiona",
		"$review.NoAuthor":                    "Usuniętych recenzji nie można przywrócić, ponieważ autor tutaj nie istnieje",
		"$review.DM":                          "Napisano nową recenzję",
	}
}
