package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.PortugueseBR] = map[string]string{
		"#admin": "administrador",
		"#admin.allow-role": "permitir-função",
		"#look": "olhar",
		"#move": "mover",
		"#review": "análise",
		"#admin.allow-role.value": "valor",
		"#.subject": "alvo",
		"#look.info": "informação",
		"#look.review-list": "lista-de-revisão",
		"#admin.allow-role.Description": "Exibir pontuações como funções. Padrão: Falso",
		"#look.Description": "Veja alguma coisa",
		"#move.Description": "Mover avaliação para este canal",
		"#review.Description": "Revisão do usuário",
		"#admin.allow-role.value.Description": "Definir valor",
		"#.subject.Description": "Selecione o alvo",
		"#look.info.Description": "Ver informações do usuário",
		"#look.review-list.Description": "Veja uma lista de avaliações recebidas pelos usuários",
		"#allow-role.NeedPermissions": "O bot não tem permissões - Gerenciar funções",
		"#allow-role.InProgress": "trabalho em progresso",
		"#allow-role.proc.Title": "Modificar opções",
		"#allow-role.proc.Description": "Permitir função",
		"#allow-role.proc.InProgress": "Processo",
		"#allow-role.proc.Done": "completo",
		"#allow-role.Keep": "Nenhuma configuração foi alterada",
		"#look.info.IsNone": "Sem comentários",
		"#look.review-list.IsNone": "Não há comentários",
		"#look.review-list.menu.Title": "Críticas para %s",
		"#look.review-list.menu.Page": "%d página",
		"#move.IsNone": "Não há comentários escritos para o alvo",
		"#move.Move": "mude para cá",
		"#review.SelfReview": "Você não pode se revisar",
		"#review.modal.Title": "Avaliações",
		"#review.lable.Score": "pontuação",
		"#review.lable.Title": "título",
		"#review.lable.Content": "detalhe",
		"$review.IsEdited": "Esta avaliação foi editada",
		"$review.NoAuthor": "As resenhas excluídas não podem ser restauradas porque o autor não existe aqui",
		"$review.DM": "Uma nova revisão foi escrita",
    }
}
