package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Romanian] = map[string]string{
		"#admin":                              "admin",
		"#admin.allow-role":                   "permite-rol",
		"#look":                               "uite",
		"#move":                               "mișcare",
		"#review":                             "revizuire",
		"#admin.allow-role.value":             "valoare",
		"#.subject":                           "ţintă",
		"#look.info":                          "informație",
		"#look.reviews":                       "recenzii",
		"#admin.allow-role.Description":       "Afișați scorurile ca roluri. Implicit: fals",
		"#look.Description":                   "vezi ceva",
		"#move.Description":                   "Mută ​​recenzia pe acest canal",
		"#review.Description":                 "Recenzie de utilizator",
		"#admin.allow-role.value.Description": "valoarea stabilită",
		"#.subject.Description":               "Selectați ținta",
		"#look.info.Description":              "Vizualizați informații despre utilizator",
		"#look.reviews.Description":           "Vezi recenziile primite de subiect",
		"#admin.allow-role.NeedPermissions":   "Bot nu are permisiuni - Gestionați roluri",
		"#admin.allow-role.InProgress":        "lucru în curs",
		"#admin.allow-role.proc.Title":        "Modificați opțiuni",
		"#admin.allow-role.proc.Description":  "Permite roluri",
		"#admin.allow-role.proc.InProgress":   "Procedură",
		"#admin.allow-role.proc.Done":         "complet",
		"#admin.allow-role.Keep":              "Nu s-au schimbat setări",
		"#look.info.IsNone":                   "Nicio recenzie",
		"#look.reviews.IsNone":                "Nu există recenzii",
		"#look.reviews.menu.Title":            "Recenzii pentru %s",
		"#look.reviews.menu.Page":             "%d pagină",
		"#move.IsNone":                        "Nu există recenzii scrise pentru țintă",
		"#move.Move":                          "muta-te aici",
		"#review.SelfReview":                  "Nu te poți revizui",
		"#review.modal.Title":                 "Examinați %s",
		"#review.lable.Score":                 "Scor",
		"#review.lable.Title":                 "titlu",
		"#review.lable.Content":               "detaliu",
		"$review.IsEdited":                    "Această recenzie a fost editată",
		"$review.NoAuthor":                    "Recenziile șterse nu pot fi restaurate deoarece autorul nu există aici",
		"$review.DM":                          "A fost scrisă o nouă recenzie",
	}
}
