package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Russian] = map[string]string{
		"#allow-role":                   "разрешено-ролью",
		"#look":                         "смотреть",
		"#move":                         "двигаться",
		"#review":                       "обзор",
		"#allow-role.value":             "ценить",
		"#.subject":                     "цель",
		"#look.info":                    "информация",
		"#look.review-list":             "список-отзывов",
		"#allow-role.Description":       "Только администратор. По умолчанию: False.",
		"#look.Description":             "увидеть что-то",
		"#move.Description":             "Переместить обзор на этот канал",
		"#review.Description":           "Обзор пользователя",
		"#allow-role.value.Description": "Установить значение",
		"#.subject.Description":         "Выберите цель",
		"#look.info.Description":        "Просмотр информации о пользователе",
		"#look.review-list.Description": "Просмотр списка отзывов, полученных пользователями",
		"#allow-role.NeedPermissions":   "У бота нет разрешений – Управление ролями",
		"#allow-role.InProgress":        "работа в процессе",
		"#allow-role.proc.Title":        "Изменить параметры",
		"#allow-role.proc.Description":  "Разрешение роли",
		"#allow-role.proc.InProgress":   "Судебное разбирательство",
		"#allow-role.proc.Done":         "полный",
		"#allow-role.Keep":              "Настройки не изменены",
		"#look.info.IsNone":             "Нет отзывов",
		"#look.review-list.IsNone":      "Нет отзывов",
		"#look.review-list.menu.Title":  "Отзывы для %s",
		"#look.review-list.menu.Page":   "%d страница",
		"#move.IsNone":                  "Для объекта не оставлено ни одного отзыва.",
		"#move.Move":                    "двигайтесь сюда",
		"#review.SelfReview":            "Вы не можете проверить себя",
		"#review.modal.Title":           "Обзор %s",
		"#review.lable.Score":           "счет",
		"#review.lable.Title":           "заголовок",
		"#review.lable.Content":         "деталь",
		"$review.IsEdited":              "Этот отзыв был отредактирован",
		"$review.NoAuthor":              "Удаленные отзывы невозможно восстановить, поскольку автора здесь не существует.",
		"$review.DM":                    "Написан новый отзыв",
	}
}
