package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.SpanishES] = map[string]string{
		"#admin":                              "administración",
		"#admin.allow-role":                   "permitir-rol",
		"#look":                               "mirar",
		"#move":                               "mover",
		"#review":                             "revisar",
		"#admin.allow-role.value":             "valor",
		"#.subject":                           "objetivo",
		"#look.info":                          "información",
		"#look.reviews":                       "opiniones",
		"#admin.allow-role.Description":       "Mostrar puntuaciones como roles. Valor predeterminado: Falso",
		"#look.Description":                   "ves algo",
		"#move.Description":                   "Mover reseña a este canal",
		"#review.Description":                 "Revisión del usuario",
		"#admin.allow-role.value.Description": "valor ajustado",
		"#.subject.Description":               "Seleccione un objetivo",
		"#look.info.Description":              "Ver información del usuario",
		"#look.reviews.Description":           "Ver las reseñas que ha recibido el tema",
		"#admin.allow-role.NeedPermissions":   "El bot carece de permisos - Administrar roles",
		"#admin.allow-role.InProgress":        "trabajo en progreso",
		"#admin.allow-role.proc.Title":        "Modificar opciones",
		"#admin.allow-role.proc.Description":  "Permitir roles",
		"#admin.allow-role.proc.InProgress":   "Proceder",
		"#admin.allow-role.proc.Done":         "completo",
		"#admin.allow-role.Keep":              "No se ha cambiado ninguna configuración",
		"#look.info.IsNone":                   "Sin reseñas",
		"#look.reviews.IsNone":                "No hay reseñas",
		"#look.reviews.menu.Title":            "Reseñas de %v",
		"#look.reviews.menu.Page":             "%v página",
		"#move.IsNone":                        "No hay reseñas escritas para el objetivo.",
		"#move.Move":                          "Muevete aquí",
		"#review.SelfReview":                  "No puedes revisarte a ti mismo",
		"#review.modal.Title":                 "Revisar %v",
		"#review.lable.Score":                 "puntaje",
		"#review.lable.Title":                 "título",
		"#review.lable.Content":               "detalle",
		"$review.IsEdited":                    "Esta reseña ha sido editada.",
		"$review.NoAuthor":                    "Las reseñas eliminadas no se pueden restaurar porque el autor no existe aquí",
		"$review.DM":                          "Se ha escrito una nueva reseña.",
	}
}
