package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Swedish] = map[string]string{
		"#admin":                              "administration",
		"#admin.allow-role":                   "tillåta-roll",
		"#look":                               "se",
		"#move":                               "flytta",
		"#review":                             "recension",
		"#admin.allow-role.value":             "värde",
		"#.subject":                           "mål",
		"#look.info":                          "information",
		"#look.reviews":                       "recensioner",
		"#admin.allow-role.Description":       "Visa poäng som roller. Standard: Falskt",
		"#look.Description":                   "se något",
		"#move.Description":                   "Flytta recensionen till den här kanalen",
		"#review.Description":                 "Användarrecension",
		"#admin.allow-role.value.Description": "satt värde",
		"#.subject.Description":               "Välj mål",
		"#look.info.Description":              "Visa användarinformation",
		"#look.reviews.Description":           "Se de recensioner ämnet har fått",
		"#admin.allow-role.NeedPermissions":   "Bot saknar behörigheter - Hantera roller",
		"#admin.allow-role.InProgress":        "pågående arbete",
		"#admin.allow-role.proc.Title":        "Ändra alternativ",
		"#admin.allow-role.proc.Description":  "Tillåt roller",
		"#admin.allow-role.proc.InProgress":   "Förfarande",
		"#admin.allow-role.proc.Done":         "komplett",
		"#admin.allow-role.Keep":              "Inga inställningar har ändrats",
		"#look.info.IsNone":                   "Inga recensioner",
		"#look.reviews.IsNone":                "Det finns inga recensioner",
		"#look.reviews.menu.Title":            "Recensioner för %v",
		"#look.reviews.menu.Page":             "%v sida",
		"#move.IsNone":                        "Det finns inga recensioner skrivna för målet",
		"#move.Move":                          "flytta hit",
		"#review.SelfReview":                  "Du kan inte recensera dig själv",
		"#review.modal.Title":                 "Granska %v",
		"#review.lable.Score":                 "Göra",
		"#review.lable.Title":                 "titel",
		"#review.lable.Content":               "detalj",
		"$review.IsEdited":                    "Denna recension har redigerats",
		"$review.NoAuthor":                    "Raderade recensioner kan inte återställas eftersom författaren inte finns här",
		"$review.DM":                          "En ny recension har skrivits",
	}
}
