package localization

import "github.com/bwmarrin/discordgo"

func init() {
	data[discordgo.Thai] = map[string]string{
		"#allow-role":                   "ได้รับอนุญาตตามบทบาท",
		"#look":                         "ดู",
		"#move":                         "เคลื่อนไหว",
		"#review":                       "ทบทวน",
		"#allow-role.value":             "ค่า",
		"#.subject":                     "เป้า",
		"#look.info":                    "ข้อมูล",
		"#look.review-list":             "รายการตรวจสอบ",
		"#allow-role.Description":       "ผู้ดูแลระบบเท่านั้น - ค่าเริ่มต้น: เท็จ",
		"#look.Description":             "เห็นอะไรบางอย่าง",
		"#move.Description":             "ย้ายรีวิวมาที่ช่องนี้",
		"#review.Description":           "รีวิวจากผู้ใช้",
		"#allow-role.value.Description": "ตั้งค่า",
		"#.subject.Description":         "เลือกเป้าหมาย",
		"#look.info.Description":        "ดูข้อมูลผู้ใช้",
		"#look.review-list.Description": "ดูรายการบทวิจารณ์ที่ได้รับจากผู้ใช้",
		"#allow-role.NeedPermissions":   "บอทขาดสิทธิ์ - จัดการบทบาท",
		"#allow-role.InProgress":        "อยู่ระหว่างดำเนินการ",
		"#allow-role.proc.Title":        "ปรับเปลี่ยนตัวเลือก",
		"#allow-role.proc.Description":  "อนุญาตบทบาท",
		"#allow-role.proc.InProgress":   "กำลังดำเนินการ",
		"#allow-role.proc.Done":         "สมบูรณ์",
		"#allow-role.Keep":              "ไม่มีการเปลี่ยนแปลงการตั้งค่า",
		"#look.info.IsNone":             "ไม่มีบทวิจารณ์",
		"#look.review-list.IsNone":      "ไม่มีบทวิจารณ์",
		"#look.review-list.menu.Title":  "บทวิจารณ์สำหรับ %s",
		"#look.review-list.menu.Page":   "%d หน้า",
		"#move.IsNone":                  "ไม่มีการเขียนบทวิจารณ์สำหรับเป้าหมาย",
		"#move.Move":                    "ย้ายมาที่นี่",
		"#review.SelfReview":            "คุณไม่สามารถทบทวนตัวเองได้",
		"#review.modal.Title":           "รีวิว %s",
		"#review.lable.Score":           "คะแนน",
		"#review.lable.Title":           "ชื่อ",
		"#review.lable.Content":         "รายละเอียด",
		"$review.IsEdited":              "รีวิวนี้ได้รับการแก้ไขแล้ว",
		"$review.NoAuthor":              "บทวิจารณ์ที่ถูกลบไม่สามารถกู้คืนได้เนื่องจากไม่มีผู้เขียนอยู่ที่นี่",
		"$review.DM":                    "มีการเขียนบทวิจารณ์ใหม่แล้ว",
	}
}
